backweb/urls.py
from django.conf.urls import url
from backweb import views

urlpatterns = [

    # 注册
    url(r'^register/', views.register),
    # 登陆
    url(r'^login/', views.login, name='login'),
    # 主页
    url(r'^index/', views.index, name='index'),
    # 创建文章
    url(r'^add/', views.add, name='add'),
    # 退出登录
    url(r'^logout/', views.logout, name='logout'),
    # 删除文章
    url(r'^del_art/(\d+)/', views.del_art, name='del_art'),
    # 编辑文章
    url(r'^edit_art/(\d+)/', views.edit_art, name='edit_art'),
    # 推荐书籍
    url(r'^recommend/', views.recommend, name='recommend'),
    # 文章类型
    url(r'^review/', views.review, name='review'),
    # 用户
    url(r'^user/', views.user, name='user'),
    # 删除用户
    url(r'^del_user/(\d+)/', views.del_user, name='del_user'),

]

blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import static

from blog.settings import MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # 导入web的urls
    url(r'^web/', include('web.urls', namespace='web')),

    # 导入backweb 的urls
    url(r'^backweb/', include('backweb.urls', namespace='art')),

]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

web/urls.py
from django.conf.urls import url
from web import views
urlpatterns = [
    url(r'^index/', views.index, name='index'),
    # 文章
    url(r'^post/', views.post, name='post'),
    # 关于作者
    url(r'^about/', views.about, name='about'),
]

templates/web/about.html
{% extends 'web/base.html' %}

{% block title %}
    肖炜的博客
{% endblock %}

{% block css %}
<link href="/static/web/css/base.css" type="text/css" rel="stylesheet"/>
<link href="/static/web/css/index.css" rel="stylesheet"/>
<link href="/static/web/css/m.css" rel="stylesheet" />
{% endblock %}


{% block content %}

        <header class="header-navigation", id="header">
			<img src="/static/web/img/logo.png">
			<nav><div class="logo"><a href="{% url 'art:login' %}">肖炜个人博客</a></div>
			<h2 id="mnavh"><span class="navicon"></span></h2>
			<ul id="starlist">
				<li><a href="{% url 'web:index' %}">网站首页</a></li>
				<li><a href="{% url 'web:post' %}">我的笔记</a></li>
				<li><a href="{% url 'web:about' %}">关于我</a></li>
			</ul>
		</nav>
		</header>
		<article>
			<aside class="l_box">
				<div class="about_me">
					<h2>关于我</h2>
					<ul>
						<i><img src="/static/web/img/tx.jpg"></i>
						<p><b>肖炜</b>,一个90后！从2016年进入大学开始了解基础的网络知识,一直都在学习计算机知识。</p>

					</ul>

				</div>
			</aside>
			<main class="r_box">
                <div class="about">
                    <p>该作者暂时没有上传信息</p>
                </div>
			</main>
		</article>
		<footer>
			<p>Design by <a href="xwytq.top" target="_blank">肖炜个人网站</a>&emsp;蜀ICP备18036499号</p>
		</footer>
{% endblock %}

templates/web/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% block css %}
    {% endblock %}

    {% block js %}
    {% endblock %}
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

templates/web/index.html
{% extends 'web/base.html' %}

{% block title %}
    肖炜的博客
{% endblock %}

{% block css %}
<link href="/static/web/css/base.css" type="text/css" rel="stylesheet"/>
<link href="/static/web/css/index.css" rel="stylesheet"/>
<link href="/static/web/css/m.css" rel="stylesheet" />
{% endblock %}


{% block content %}

        <header class="header-navigation", id="header">
			<img src="/static/web/img/logo.png">
			<nav><div class="logo"><a href="{% url 'art:login' %}">肖炜个人博客</a></div>
			<h2 id="mnavh"><span class="navicon"></span></h2>
			<ul id="starlist">
				<li><a href="{% url 'web:index' %}">网站首页</a></li>
				<li><a href="{% url 'web:post' %}">我的笔记</a></li>
				<li><a href="{% url 'web:about' %}">关于我</a></li>
			</ul>
		</nav>
		</header>
		<article>
			<aside class="l_box">
				<div class="about_me">
					<h2>关于我</h2>
					<ul>
						<i><img src="/static/web/img/tx.jpg"></i>
						<p><b>肖炜</b>,一个90后！从2016年进入大学开始了解基础的网络知识,一直都在学习计算机知识。</p>

					</ul>

				</div>
				<div class="fenlei">
					<h2>文章分类</h2>
					<ul>
                        {% for type,value in dict.items %}
						<li>{{ type.t_name }}&nbsp;({{value}})</li>
                        {% endfor %}

					</ul>
				</div>
			</aside>
			<main class="r_box">
                {% for art in pages %}
				<li>
					<i><a href=""><img src="/static/web/img/tx.jpg"></a></i>
					<h3><a href="">{{ art.title }}</a></h3>
					<p><a href="">{{ art.desc }}</a></p>
				</li>
                {% endfor %}
			</main>
		</article>
		<footer>
			<p>Design by <a href="xwytq.top" target="_blank">肖炜个人网站</a>&emsp;蜀ICP备18036499号</p>
		</footer>
{% endblock %}

templates/web/list.html
{% extends 'web/base.html' %}

{% block title %}
    肖炜的博客
{% endblock %}

{% block css %}
<link href="/static/web/css/base.css" type="text/css" rel="stylesheet"/>
<link href="/static/web/css/index.css" rel="stylesheet"/>
<link href="/static/web/css/m.css" rel="stylesheet" />
{% endblock %}


{% block content %}

        <header class="header-navigation", id="header">
			<img src="/static/web/img/logo.png">
			<nav><div class="logo"><a href="{% url 'art:login' %}">肖炜个人博客</a></div>
			<h2 id="mnavh"><span class="navicon"></span></h2>
			<ul id="starlist">
				<li><a href="{% url 'web:index' %}">网站首页</a></li>
				<li><a href="{% url 'web:post' %}">我的笔记</a></li>
				<li><a href="{% url 'web:about' %}">关于我</a></li>
			</ul>
		</nav>
		</header>
		<article>
			<aside class="l_box">
				<div class="search">
                    <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
                        <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
                        <input name="show" value="title" type="hidden">
                        <input name="tempid" value="1" type="hidden">
                        <input name="tbname" value="news" type="hidden">
                        <input name="Submit" class="input_submit" value="搜索" type="submit">
                    </form>
                </div>
				<div class="fenlei">
					<h2>文章分类</h2>
					<ul>
                        {% for type,value in dict.items %}
						<li>{{ type.t_name }}&nbsp;({{value}})</li>
                        {% endfor %}

					</ul>
				</div>
			</aside>
			<main class="r_box">
                {% for art in pages %}
				<li>
					<i><a href=""><img src="/static/web/img/tx.jpg"></a></i>
					<h3><a href="">{{ art.title }}</a></h3>
					<p><a href="">{{ art.desc }}</a></p>
				</li>
                {% endfor %}
			</main>
		</article>
		<footer>
			<p>Design by <a href="xwytq.top" target="_blank">肖炜个人网站</a>&emsp;蜀ICP备18036499号</p>
		</footer>
{% endblock %}