backweb/urls.py
from django.conf.urls import url
from backweb import views

urlpatterns = [

    # 注册
    url(r'^register/', views.register),
    # 登陆
    url(r'^login/', views.login, name='login'),
    # 主页
    url(r'^index/', views.index, name='index'),
    # 创建文章
    url(r'^add/', views.add, name='add'),
    # 退出登录
    url(r'^logout/', views.logout, name='logout'),
    # 删除文章
    url(r'^del_art/(\d+)/', views.del_art, name='del_art'),
    # 编辑文章
    url(r'^edit_art/(\d+)/', views.edit_art, name='edit_art'),
    # 推荐书籍
    url(r'^recommend/', views.recommend, name='recommend'),
    # 文章类型
    url(r'^review/', views.review, name='review'),
    # 用户
    url(r'^user/', views.user, name='user'),
    # 删除用户
    url(r'^del_user/(\d+)/', views.del_user, name='del_user'),

]

blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import static

from blog.settings import MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # 导入web的urls
    url(r'^web/', include('web.urls', namespace='web')),

    # 导入backweb 的urls
    url(r'^backweb/', include('backweb.urls', namespace='art')),

]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

web/urls.py
from django.conf.urls import url
from web import views
urlpatterns = [
    url(r'^index/', views.index, name='index'),
    # 文章
    url(r'^post/', views.post, name='post'),
    # 关于作者
    url(r'^about/', views.about, name='about'),
]

backweb/models.py
from django.db import models


class MyUser(models.Model):
    username = models.CharField(max_length=10, unique=True)
    password = models.CharField(max_length=100)
    create_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'user'


class ArticleType(models.Model):
    t_name = models.CharField(max_length=20, unique=True)
    create_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'article_type'


class Article(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=20)
    desc = models.CharField(max_length=100)
    content = models.TextField(null=True)
    upload_time = models.DateTimeField(auto_now_add=True)
    tf = models.ForeignKey(ArticleType)

    class Meta:
        db_table = 'article'

backweb/views.py
from django.core.paginator import Paginator
from django.db.models import Count
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from backweb.Artform import AddArtForm, EditArtForm
from backweb.models import MyUser, ArticleType, Article


def register(request):
    if request.method == 'GET':
        return render(request, 'backweb/register.html')

    # 注册验证
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        password2 = request.POST.get('password2')

    # 1.判断用户存不存在，用户是否已经被注册
    user = MyUser.objects.filter(username=username).first()
    if username:
        if user:
            err_name = '该用户名已经存在，请重新输入'
            return render(request, 'backweb/register.html', {'err_name': err_name})
    else:
        err_name = '用户名不能为空'
        return render(request, 'backweb/register.html', {'err_name': err_name})
    # 2.判断密码和确认密码是否一致
    if password and password2:
        if not password == password2:
            err_pwd = '密码和确认密码不一致'
            return render(request, 'backweb/register.html', {'err_pwd': err_pwd})
    elif not password:
        err_pwd = '密码不能为空'
        return render(request, 'backweb/register.html', {'err_pwd': err_pwd})
    elif not password2:
        err_pwd = '确认密码不能为空'
        return render(request, 'backweb/register.html', {'err_pwd': err_pwd})
    # 3、用户名不存在且不为空，密码与确认密码相同时，保存在user表中
    MyUser.objects.create(username=username, password=password)
    return HttpResponseRedirect('/backweb/login/')


def login(request):
    if request.method == 'GET':
        return render(request, 'backweb/login.html')

    if request.method == 'POST':
        # 获取用户名
        username = request.POST.get('username')
        password = request.POST.get('password')

    # 1.查询数据库中的用户名和密码对应的用户对象
    user = MyUser.objects.filter(username=username, password=password).first()
    if not user:
        err_user = '用户名/密码错误'
        return render(request, 'backweb/login.html', {'err_user': err_user})

    # 使用session实现登录操作
    request.session['user_id'] = user.id

    # 跳转到首页
    return HttpResponseRedirect('/backweb/index/')





def add(request):
    if request.method == 'GET':
        return render(request, 'backweb/add.html')
    if request.method == 'POST':
        form = AddArtForm(request.POST, request.FILES)
        if form.is_valid():
            title = form.cleaned_data['title']
            author = form.cleaned_data['author']
            desc = form.cleaned_data['desc']
            content = form.cleaned_data['content']
            tf = request.POST.get('tf')
            tf_id = ArticleType.objects.filter(pk=tf).first()
            if tf_id:
                Article.objects.create(title=title, author=author, desc=desc, content=content, tf=tf_id)
                return HttpResponseRedirect('/backweb/index/')
            else:
                err_name = '没有此类型'
                return render(request, 'backweb/add.html', {'err_name': err_name})
        else:
            return render(request, 'backweb/add.html', {'form': form})


def logout(request):
    request.session.flush()
    return HttpResponseRedirect('/backweb/logout/')


def del_art(request, id):
    if request.method == 'GET':
        Article.objects.filter(pk=id).delete()
        return HttpResponseRedirect('/backweb/index/')


def edit_art(request, id):
    if request.method == 'GET':
        article = Article.objects.filter(pk=id).first()
        return render(request, 'backweb/add.html', {'article': article})
    if request.method == 'POST':
        form = EditArtForm(request.POST, request.FILES)
        if form.is_valid():
            # 验证成功
            title = form.cleaned_data['title']
            author = form.cleaned_data['author']
            desc = form.cleaned_data['desc']
            content = form.cleaned_data['content']
            tf = request.POST.get('f')
            article = Article.objects.filter(pk=id).first()
            tf_id = ArticleType.objects.filter(pk=tf).first()
            if tf_id:
                article.title = title
                article.author = author
                article.desc = desc
                article.content = content
                article.f = tf_id
                article.save()
                return HttpResponseRedirect('/backweb/index/')
            else:
                err_name = '没有此类型'
                return render(request, 'backweb/add.html', {'err_name': err_name})
        else:
            # 验证失败
            article = Article.objects.filter(pk=id).first()
            return render(request, 'backweb/add.html',
                          {'form': form, 'article': article})


def index(request):
    if request.method == 'GET':
        page = int(request.GET.get('page', 1))
        articles = Article.objects.all()
        # 将所有的数据按照每一页5条数据进行切块处理
        paginator = Paginator(articles, 10)
        # 获取页面的第几条数据
        pages = paginator.page(page)
        articles = Article.objects.all()
        return render(request, 'backweb/index.html', {'pages': pages, 'articles': articles})


def recommend(request):
    if request.method == 'GET':
        return render(request, 'backweb/recommend.html')


def review(request):
    if request.method == 'GET':
        types = ArticleType.objects.all().order_by('id')
        t = types.values('id')
        lists = []
        for i in t:
            art = Article.objects.filter(tf=i['id']).aggregate(Count('tf'))

            lists += art.values()
            continue
        dict = {}
        for num in range(len(types)):
            dict[types[num]] = lists[num]

        return render(request, 'backweb/atype.html', {'dict': dict})


def user(request):
    if request.method == 'GET':
        page = int(request.GET.get('page', 1))
        users = MyUser.objects.all()
        # 将所有的数据按照每一页5条数据进行切块处理
        paginator = Paginator(users, 5)
        # 获取页面的第几条数据
        pages = paginator.page(page)

        return render(request, 'backweb/user.html', {'pages': pages, 'users': users})


def del_user(request, id):
    if request.method == 'GET':
        MyUser.objects.filter(pk=id).delete()
        return HttpResponseRedirect('/backweb/user/')

templates/backweb/add.html
{% extends 'backweb/base.html' %}

{% block title %}
   添加文章
{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="/static/backweb/css/sty.css">
{% endblock %}

{% block js %}
    {% load static %}
    <script src="{% static 'kindeditor/kindeditor-all-min.js' %}" ></script>
    <script src="{% static 'kindeditor/lang/zh-CN.js' %}"></script>
    <script type="text/javascript">
        KindEditor.ready(function(K) {
            window.editor = K.create('#editor_id',{
                uploadJson:'/util/upload/kindeditor'
            });
        });
    </script>
{% endblock %}

{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p>标题：<input type="text" name="title" value="{{ article.title }}"></p>{{ form.errors.title }}
    <p>作者：<input type="text" name="author" value="{{ article.author }}"></p>{{ form.errors.author }}
    <p>简述：<input type="text" name="desc" value="{{ article.desc }}"></p>{{ form.errors.desc }}
    <p>内容：<textarea id="editor_id" name="content" >{{ article.content }}</textarea></p>{{ form.errors.content}}
    <p>类别：<input type="number" name="tf" placeholder="输入(1~5)">{{ article.tf }}</p>{{ err_name }}
    <input id="sub" type="submit" value="提交">
</form>
{% endblock %}

templates/backweb/atype.html
{% extends 'backweb/base.html' %}

{% block title %}
    首页
{% endblock %}


{% block css %}
<link rel="stylesheet" type="text/css" href="/static/backweb/css/sty.css">
<link rel="stylesheet" type="text/css" href="/static/backweb/css/atype.css">

{% endblock %}

{% block content %}
    {% csrf_token %}
    <div id="logo">

    </div>
      <div class="header">
        <div id="btn">
          <input type="text" placeholder="输入关键字搜索" >
            <button type="submit">搜索</button>
          </div>
          <ul>
            <li id="news"><a href="" onClick="if(!confirm('改功能尚未开发，请等待'))return false;">消息</a></li>
            <li><a href=""  onClick="if(!confirm('暂时无法查询个人信息！'))return false;"> {{ user.username }}</a></li>
            <li><a href="{% url 'art:logout' %}" onClick="if(!confirm('是否确认退出？'))return false;">退出登录</a></li>
            <li><a href="" onClick="if(!confirm('改功能尚未开发，请等待'))return false;">帮助</a></li>

          </ul>

       </div>

  <div id="comment">
        <div id="left">
          <ul>
            <li><a href="{% url 'art:index' %}">文章</a></li>
          </ul>
            <ul>
                <li><a href="{% url 'art:recommend' %}">推荐</a></li>
            </ul>
            <ul>
                <li id="review"><a href="" onClick="if(!confirm('改功能尚未开发，请等待'))return false;">评论</a></li>
            </ul>
            <ul>
                <li><a href="{% url 'art:review' %}">类型</a></li>
            </ul>

          <ul>
              <li><a href="{% url 'art:user' %}">用户</a></li>
          </ul>
          <ul>
              <li><a href="" onClick="if(!confirm('改功能尚未开发，请等待'))return false;">设置</a></li>
          </ul>

        </div>
      <div id="content">
         <h4 id="book">文章类型</h4>
        <hr>
        <table>
            <tbody>
                <tr id="tp">
                    <td>编号</td>
                    <td>课程</td>
                    <td>数量</td>
                </tr>
                {% for type,value in dict.items %}
                    <tr id="tp1">
                        <td>{{ forloop.counter }}</td>
                        <td>{{ type.t_name }}</td>
                        <td>{{ value }}</td>
                    </tr>
                {% endfor %}

            </tbody>

        </table>

      </div>


  </div>

  {% block js %}

  {% endblock %}
{% endblock %}

templates/backweb/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>
        {% block title %}
        {% endblock %}

    </title>
    {% block css %}
    <link rel="stylesheet" href="/static/backweb/css/bootstrap.min.css">

    {% endblock %}

    {% block js %}
        <script src="/static/backweb/js/jquery-1.11.1.min.js" type="text/javascript"></script>
        <script src="/static/backweb/js/html5shiv.min.js" type="text/javascript"></script>
        <script src="/static/backweb/js/respond.min.js" type="text/javascript"></script>
        <script src="/static/backweb/js/selectivizr-min.js" type="text/javascript"></script>
        <script src="/static/backweb/js/bootstrap.min.js"></script>
        <script src="/static/backweb/js/admin-scripts.js"></script>
    {% endblock %}



</head>
<body>
{% block content %}
{% endblock %}

</body>
</html>

templates/backweb/index.html
{% extends 'backweb/base.html' %}

{% block title %}
    首页
{% endblock %}


{% block css %}
<link rel="stylesheet" type="text/css" href="/static/backweb/css/sty.css">
{% endblock %}

{% block content %}
    {% csrf_token %}

      <div class="header">
          <div id="btn">
              <input type="text" placeholder="输入关键字搜索" >
              <button type="submit">搜索</button>
          </div>
          <ul>
            <li id="news"><a href="" onClick="if(!confirm('改功能尚未开发，请等待'))return false;">消息</a></li>
            <li><a href=""  onClick="if(!confirm('暂时无法查询个人信息！'))return false;"> {{ user.username }}</a></li>
            <li><a href="{% url 'art:logout' %}" onClick="if(!confirm('是否确认退出？'))return false;">退出登录</a></li>
            <li><a href="" onClick="if(!confirm('改功能尚未开发，请等待'))return false;">帮助</a></li>

          </ul>

       </div>

  <div id="comment">
        <div id="left">
          <ul>
            <li><a href="{% url 'art:index' %}">文章</a></li>
          </ul>
            <ul>
                <li><a href="{% url 'art:recommend' %}">推荐</a></li>
            </ul>
            <ul>
                <li><a href="" onClick="if(!confirm('改功能尚未开发，请等待'))return false;">评论</a></li>
            </ul>
            <ul>
                <li><a href="{% url 'art:review' %}">类型</a></li>
            </ul>

          <ul>
              <li><a href="{% url 'art:user' %}">用户</a></li>
          </ul>
          <ul>
              <li><a href="" onClick="if(!confirm('改功能尚未开发，请等待'))return false;">设置</a></li>
          </ul>

        </div>
      <div id="content">
         <h4>文章总览</h4>
          <p id="center">提示：类型中1表示Python，2表示HTML5, 3表示MySQL, 4表示Django，5表示flask。</p>
          <p id="add"><a href="{% url 'art:add' %}">添加文章</a></p>
        <hr>
        <table>
            <tbody>
                <tr id="th">
                    <td>编号</td>
                    <td>标题</td>
                    <td>作者</td>
                    <td>简述</td>
                    <td>操作</td>
                </tr>

            {% for art in pages %}
                <tr id="th2">
                    <td>{{ forloop.counter }}</td>
                    <td>{{ art.title }}</td>
                    <td>{{ art.author }}</td>
                    <td>{{ art.desc }}</td>
                    <td>
                        <a href="{% url 'art:edit_art' art.id %}">编辑</a>
                        <a href="{% url 'art:del_art' art.id %}">删除</a>
                    </td>


                </tr>

                {% endfor %}
            </tbody>

        </table>
          <div id="page">
              <p id="pg">
                  共 {{ pages.paginator.num_pages }} 页
                  当前 {{ pages.number }} 页
                  共 {{ pages.paginator.count }} 条数据
                  <a href="{% url 'art:index' %}?page={{ 1 }}">首页</a>
                  {% if pages.has_previous %}
                  <a href="{% url 'art:index' %}?page={{ pages.previous_page_number }}">上一页</a>
                  {% endif %}
                  {% for i in pages.paginator.page_range %}
                    <a href="{% url 'art:index' %}?page={{ i }}">{{ i }}</a>
                  {% endfor %}
                  {% if pages.has_next %}
                  <a href="{% url 'art:index' %}?page={{ pages.next_page_number }}">下一页</a>

                  {% endif %}
                  <a href="{% url 'art:index' %}?page={{ pages.paginator.num_pages }}">尾页</a>


              </p>

          </div>

      </div>


  </div>

  {% block js %}

  {% endblock %}
{% endblock %}

templates/backweb/login.html
{% extends 'backweb/base.html' %}
    {% block title %}
        登录
    {% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="/static/backweb/css/login.css">
{% endblock %}

{% block content %}

    <form action="" method="post">
        <p id="login">login</p>
        <div>
            {{ err_user }}
            {% csrf_token %}
        <p>账户：<input type="text" name="username" placeholder="请输入你的账号"></p>
        <p>密码：<input type="password" name="password" placeholder="请输入密码"></p>
        </div>
        <p id="submit"><button>登录</button></p>
    </form>
{% block js %}
{% endblock %}
{% endblock %}

templates/backweb/recommend.html
{% extends 'backweb/base.html' %}

{% block title %}
    推荐
{% endblock %}


{% block css %}
<link rel="stylesheet" type="text/css" href="/static/backweb/css/sty.css">
{% endblock %}

{% block content %}
    {% csrf_token %}
    <div id="logo">

    </div>
      <div class="header">
        <div id="btn">
          <input type="text" placeholder="输入关键字搜索" >
            <button type="submit">搜索</button>
          </div>
          <ul>
            <li id="news"><a href="" onClick="if(!confirm('改功能尚未开发，请等待'))return false;">消息</a></li>
            <li><a href=""  onClick="if(!confirm('暂时无法查询个人信息！'))return false;"> {{ user.username }}</a></li>
            <li><a href="{% url 'art:logout' %}" onClick="if(!confirm('是否确认退出？'))return false;">退出登录</a></li>
            <li><a href="" onClick="if(!confirm('改功能尚未开发，请等待'))return false;">帮助</a></li>

          </ul>

       </div>

  <div id="comment">
        <div id="left">
          <ul>
            <li><a href="{% url 'art:index' %}">文章</a></li>
          </ul>
            <ul>
                <li><a href="{% url 'art:recommend' %}">推荐</a></li>
            </ul>
            <ul>
                <li id="review"><a href="" onClick="if(!confirm('改功能尚未开发，请等待'))return false;">评论</a></li>
            </ul>
            <ul>
                <li><a href="{% url 'art:review' %}">类型</a></li>
            </ul>

          <ul>
              <li><a href="{% url 'art:user' %}">用户</a></li>

          </ul>
          <ul>
              <li><a href="" onClick="if(!confirm('改功能尚未开发，请等待'))return false;">设置</a></li>

          </ul>

        </div>
      <div id="content">
         <h4 id="book">推荐书籍</h4>
        <hr>
          <div id="rec">
              <p><img src="/static/backweb/img/01.jpg" alt=""></p>
              <p><img src="/static/backweb/img/02.jpg" alt=""></p>
              <p><img src="/static/backweb/img/03.jpg" alt=""></p>
              <p><img src="/static/backweb/img/04.jpg" alt=""></p>
              <p><img src="/static/backweb/img/05.jpg" alt=""></p>
              <p><img src="/static/backweb/img/06.jpg" alt=""></p>
              <p><img src="/static/backweb/img/07.jpg" alt=""></p>
              <p><img src="/static/backweb/img/08.jpg" alt=""></p>
              <p><img src="/static/backweb/img/09.jpg" alt=""></p>
              <p><img src="/static/backweb/img/10.jpg" alt=""></p>
          </div>

      </div>


  </div>
  {% block js %}

  {% endblock %}
{% endblock %}

templates/backweb/register.html
{% extends 'backweb/base.html' %}

{% block title %}
    注册
{% endblock %}

{% block css %}
{% endblock %}


{% block content %}
    {{ err_name }}
    {{ err_pwd }}
    <form action="" method="post">
        {% csrf_token %}
        <p>用户名：<input type="text" name="username" placeholder="请输入账号"></p>
        <p>密码：<input type="password" name="password" placeholder="请输入密码"></p>
        <p>确认密码：<input type="password" name="password2" placeholder="请再次输入密码"></p>
        <p><input type="submit" value="注册"></p>
    </form>

{% endblock %}

templates/backweb/user.html
{% extends 'backweb/base.html' %}

{% block title %}
    首页
{% endblock %}


{% block css %}
<link rel="stylesheet" type="text/css" href="/static/backweb/css/sty.css">
{% endblock %}

{% block content %}
    {% csrf_token %}
    <div id="logo">

    </div>
      <div class="header">
        <div id="btn">
          <input type="text" placeholder="输入关键字搜索" >
            <button type="submit">搜索</button>
          </div>
          <ul>
            <li id="news"><a href="" onClick="if(!confirm('改功能尚未开发，请等待'))return false;">消息</a></li>
            <li><a href=""  onClick="if(!confirm('暂时无法查询个人信息！'))return false;"> {{ user.username }}</a></li>
            <li><a href="{% url 'art:logout' %}" onClick="if(!confirm('是否确认退出？'))return false;">退出登录</a></li>
            <li><a href="" onClick="if(!confirm('改功能尚未开发，请等待'))return false;">帮助</a></li>

          </ul>

       </div>

  <div id="comment">
        <div id="left">
          <ul>
            <li><a href="{% url 'art:index' %}">文章</a></li>
          </ul>
            <ul>
                <li><a href="{% url 'art:recommend' %}">推荐</a></li>
            </ul>
            <ul>
                <li><a href="" onClick="if(!confirm('改功能尚未开发，请等待'))return false;">评论</a></li>
            </ul>
            <ul>
                <li><a href="{% url 'art:review' %}">类型</a></li>
            </ul>

          <ul>
              <li><a href="{% url 'art:user' %}">用户</a></li>

          </ul>
          <ul>
            <li><a href="" onClick="if(!confirm('改功能尚未开发，请等待'))return false;">设置</a>
            </li>
          </ul>

        </div>
      <div id="content">
         <h4 id="book">用户总览</h4>
        <hr>
        <table>
            <tbody>
                <tr id="th">
                    <td>编号</td>
                    <td>用户名</td>
                    <td>密码</td>
                    <td>创建时间</td>
                    <td>操作</td>
                </tr>

                {% for user in users %}
                <tr id="th2">
                    <td>{{ forloop.counter }}</td>
                    <td>{{ user.username }}</td>
                    <td>{{ user.password }}</td>
                    <td>{{ user.create_time }}</td>
                    <td>
                        <a href="{% url 'art:del_user' user.id %}">删除</a>
                    </td>


                </tr>

                {% endfor %}
            </tbody>

        </table>
          <div id="page">
              <p id="pg">
                  共 {{ pages.paginator.num_pages }} 页
                  当前 {{ pages.number }} 页
                  共 {{ pages.paginator.count }} 条数据
                  <a href="{% url 'art:index' %}?page={{ 1 }}">首页</a>
                  {% if pages.has_previous %}
                  <a href="{% url 'art:index' %}?page={{ pages.previous_page_number }}">上一页</a>
                  {% endif %}
                  {% for i in pages.paginator.page_range %}
                    <a href="{% url 'art:index' %}?page={{ i }}">{{ i }}</a>
                  {% endfor %}
                  {% if pages.has_next %}
                  <a href="{% url 'art:index' %}?page={{ pages.next_page_number }}">下一页</a>

                  {% endif %}
                  <a href="{% url 'art:index' %}?page={{ pages.paginator.num_pages }}">尾页</a>


              </p>

          </div>

      </div>


  </div>

  {% block js %}

  {% endblock %}
{% endblock %}